import type { HierarchyReport } from '../types';
import { round } from '../typography/parse';
import { rem, quoteIfNeeded, uniqueFamilies } from './css-vars';

export function exportScss(report: HierarchyReport): string {
  const lines: string[] = [];
  lines.push('// Generated by Typography Inspector');
  lines.push('');

  const families = uniqueFamilies(report);
  for (const f of families) {
    const stack = [f.primary, ...f.fallback].map(quoteIfNeeded).join(', ');
    lines.push(`$font-family-${f.slug}: ${stack};`);
  }
  if (families.length) lines.push('');

  for (const e of report.entries) {
    const r = e.role;
    lines.push(`$font-${r}-size: ${rem(e.fontSizePx)};`);
    if (e.lineHeightRatio != null) {
      lines.push(`$font-${r}-line-height: ${round(e.lineHeightRatio, 3)};`);
    }
    lines.push(`$font-${r}-weight: ${e.fontWeight};`);
    if (e.letterSpacingEm !== 0) {
      lines.push(`$font-${r}-letter-spacing: ${round(e.letterSpacingEm, 3)}em;`);
    }
    if (e.textTransform && e.textTransform !== 'none') {
      lines.push(`$font-${r}-text-transform: ${e.textTransform};`);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}
